### ISSUE TITLE
Will not work

### ISSUE THREAD

**Issue by alienatorZ** [trueinteractions/tint-chromium#15]
I recently downloaded and tried using Chromium as my Webview but got an error:

module.js:338
    throw err;
          ^
Error: Cannot find module './win/Chromium.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\A\Downloads\tint2app\node_modules\chromium\index.js:3:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

I am on Windows 8.1 

Thanks!

**Comment by alienatorZ** [comment]
> chromium@3.2171.3003 install C:\Users\Adam\AppData\Roaming\npm\node_modules\chromium
> node install.js

Fetching Installer
Installing ChromiumEmbedded
Attempting to resolve dependency 'CefSharp.Common (= 39.0.1)'.
Attempting to resolve dependency 'cef.redist.x86 (= 3.2171.2069)'.
Attempting to resolve dependency 'cef.redist.x64 (= 3.2171.2069)'.
Installing 'cef.redist.x86 3.2171.2069'.
Successfully installed 'cef.redist.x86 3.2171.2069'.
Installing 'cef.redist.x64 3.2171.2069'.
Successfully installed 'cef.redist.x64 3.2171.2069'.
Installing 'CefSharp.Common 39.0.1'.
Successfully installed 'CefSharp.Common 39.0.1'.
Installing 'CefSharp.Wpf 39.0.1'.
Successfully installed 'CefSharp.Wpf 39.0.1'.
        1 file(s) copied.
chromium@3.2171.3003 C:\Users\A\AppData\Roaming\npm\node_modules\chromium


Also my install log..

**Comment by JohnLouderback** [comment]
Are you installing the module globally? You should not be.

**Comment by alienatorZ** [comment]
At first I did not. I got the same error. I then used the -g option but still got the same error.

It is in the tint app directory but from what I see there is no ./win/ directory with Chromium.js

**Comment by trevorlinton** [comment]
@alienatorZ So if i understand this correctly, its not when you install it via npm, its when you try to do require('Chromium') in your script that you get this error?

**Comment by JohnLouderback** [comment]
I was running into this as well, but it appears the most recent change to "index.js" rectified the issue. However, now I'm seeing the below error:
```
Error: System.Reflection.ReflectionTypeLoadException Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at CLR.LoadAssembly(FunctionCallbackInfo<v8::Value>* args)
    at Error (native)
    at importOnto (Bridge.js:354:22)
    at Object.imports (Bridge.js:366:5)
    at D:\Projects\Tint Tests\Chromium\node_modules\chromium\Chromium.js:10:31
    at Object.<anonymous> (D:\Projects\Tint Tests\Chromium\node_modules\chromium\Chromium.js:215:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

My guess is the that the recent release CefSharp broke this.

**Comment by trevorlinton** [comment]
This has been fixed with the new npm publish and latest commit. 

Although since we auto-pull CefSharp at the latest version it will continue to break on every release of CefSharp, i will leave this bug open until we have a long term solution that fixes this... :/

**Comment by JohnLouderback** [comment]
Thanks for looking into this. Should I encounter this error again, are there steps I can take myself to resolve the issue? Is this an entry point issue with the DLL changing?

Thanks!
